---
Name: csp_extensions
---
NSWDPC\Utilities\ContentSecurityPolicy\Policy:
  run_in_admin: false
  max_age: 10886400
  include_subdomains: true
  whitelisted_controllers:
    - TimedNoticeController
Page:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\PageExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\SiteTreeExtension
SilverStripe\Control\Controller:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ControllerExtension
# report removal job
NSWDPC\Utilities\ContentSecurityPolicy\PruneViolationReportsJob:
  older_than: 1
