---
Name: csp_extensions
After:
  - 'framework/*'
  - 'cms/*'
---
CspPolicy:
  include_report_to: false
  run_in_admin: false
  max_age: 10886400
  include_subdomains: true
  whitelisted_controllers:
    - TimedNoticeController
SiteTree:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\SiteTreeExtension
Controller:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ControllerExtension
SilverStripe\Security\Security:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ContentSecurityPolicyEnable
# report removal job
NSWDPC\Utilities\ContentSecurityPolicy\PruneViolationReportsJob:
  older_than: 1
---
Name: csp_policy_dynamiccache_headers
Only:
  ModuleExists: dynamiccache
---
# When dynamiccache module is installed, update the headers to allow caching CSP related headers
DynamicCache:
  cacheHeaders: '/^((X\-)|(Content\-Type)|(Cache\-Control)|(Etag)|(Expires)|(Last\-Modified)|(Location)|(Content\-Security\-Policy)|(Content\-Security\-Policy\-Report\-Only)|(Report\-To))/i'
