---
Name: csp_extensions
After:
  - 'framework/*'
  - 'cms/*'
---
NSWDPC\Utilities\ContentSecurityPolicy\CspPolicy:
  run_in_admin: false
  max_age: 10886400
  whitelisted_controllers:
    - TimedNoticeController
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\SiteTreeExtension
SilverStripe\Control\Controller:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ControllerExtension
# report removal job
NSWDPC\Utilities\ContentSecurityPolicy\PruneViolationReportsJob:
  older_than: 1
