---
Name: csp_extensions
---
NSWDPC\Utilities\ContentSecurityPolicy\Policy:
  include_report_to: false
  run_in_admin: false
  max_age: 10886400
  include_subdomains: true
  whitelisted_controllers:
    -
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\SiteTreeExtension
SilverStripe\Control\Controller:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ControllerExtension
SilverStripe\Security\Security:
  extensions:
    - NSWDPC\Utilities\ContentSecurityPolicy\ContentSecurityPolicyEnable
# report removal job
NSWDPC\Utilities\ContentSecurityPolicy\PruneViolationReportsJob:
  older_than: 1
